name: nighttime-lights
channels:
  - conda-forge
  - defaults
dependencies:
  # Main Python
  - python=3.7.6
  # Scientific computing
  - numpy
  - pandas
  # Spatial packages
  - geopandas
  - rasterio
  - earthpy
